import { defineField, defineType } from "sanity";

export const regulationSchema = defineType({
  name: "regulation",
  type: "document",
  title: "Regulation",
  fields: [
    defineField({ name: "title", type: "string", validation: (R) => R.required().max(300) }),
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (R) => R.required(),
    }),
    defineField({
      name: "category",
      type: "string",
      title: "Category (e.g. Undang-Undang, Peraturan Menteri)",
      validation: (R) => R.required(),
    }),
    defineField({ name: "subCategory", type: "string" }),
    defineField({
      name: "description",
      type: "text",
      rows: 3,
      validation: (R) => R.required().max(400),
    }),
    defineField({ name: "longDescription", type: "array", of: [{ type: "block" }] }),
    defineField({ name: "coverImage", type: "image", options: { hotspot: true } }),
    defineField({ name: "file", type: "file", title: "Regulation document (PDF)" }),
    defineField({ name: "youtubeUrl", type: "url" }),
    defineField({
      name: "viewer",
      type: "string",
      options: {
        list: [
          { title: "PDF", value: "pdf" },
          { title: "Slides", value: "slides" },
          { title: "Image", value: "image" },
          { title: "Video", value: "video" },
          { title: "Web", value: "web" },
        ],
        layout: "radio",
      },
      initialValue: "pdf",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "fileType",
      type: "string",
      options: { list: ["PDF", "PPTX", "DOCX", "Web", "Slides", "Video", "Image"] },
      initialValue: "PDF",
    }),
    defineField({
      name: "jurisdiction",
      type: "string",
      title: "Jurisdiction (e.g. Nasional, Pemerintah Pusat)",
    }),
    defineField({ name: "effectiveDate", type: "date", title: "Effective date" }),
    defineField({
      name: "date",
      type: "date",
      title: "Publication date",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "regulasiStatus",
      type: "string",
      title: "Regulation status",
      options: { list: ["Berlaku", "Dicabut", "Direvisi"] },
      initialValue: "Berlaku",
    }),
    defineField({ name: "author", type: "string", title: "Issuing body" }),
    defineField({ name: "pages", type: "number" }),
    defineField({ name: "fileSize", type: "string" }),
    defineField({ name: "language", type: "string", initialValue: "Bahasa Indonesia" }),
    defineField({ name: "readTime", type: "string" }),
    defineField({
      name: "tags",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "status",
      type: "string",
      title: "Display status",
      options: { list: ["Aktif", "Aktif Terbaru", "Arsip"] },
      initialValue: "Aktif",
    }),
    defineField({ name: "published", type: "boolean", initialValue: true }),
  ],
  preview: {
    select: { title: "title", subtitle: "category", media: "coverImage" },
  },
});
