/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PustakaRegulasiRouteImport } from './routes/pustaka-regulasi'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as ManualHubRouteImport } from './routes/manual-hub'
import { Route as InsightHubRouteImport } from './routes/insight-hub'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioSplatRouteImport } from './routes/studio.$'
import { Route as PustakaRegulasiSlugRouteImport } from './routes/pustaka-regulasi_.$slug'
import { Route as ManualHubSlugRouteImport } from './routes/manual-hub_.$slug'
import { Route as InsightHubSlugRouteImport } from './routes/insight-hub_.$slug'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PustakaRegulasiRoute = PustakaRegulasiRouteImport.update({
  id: '/pustaka-regulasi',
  path: '/pustaka-regulasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualHubRoute = ManualHubRouteImport.update({
  id: '/manual-hub',
  path: '/manual-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightHubRoute = InsightHubRouteImport.update({
  id: '/insight-hub',
  path: '/insight-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/studio/$',
  path: '/studio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PustakaRegulasiSlugRoute = PustakaRegulasiSlugRouteImport.update({
  id: '/pustaka-regulasi_/$slug',
  path: '/pustaka-regulasi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualHubSlugRoute = ManualHubSlugRouteImport.update({
  id: '/manual-hub_/$slug',
  path: '/manual-hub/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightHubSlugRoute = InsightHubSlugRouteImport.update({
  id: '/insight-hub_/$slug',
  path: '/insight-hub/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/insight-hub': typeof InsightHubRoute
  '/manual-hub': typeof ManualHubRoute
  '/panduan': typeof PanduanRoute
  '/pustaka-regulasi': typeof PustakaRegulasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/insight-hub/$slug': typeof InsightHubSlugRoute
  '/manual-hub/$slug': typeof ManualHubSlugRoute
  '/pustaka-regulasi/$slug': typeof PustakaRegulasiSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/insight-hub': typeof InsightHubRoute
  '/manual-hub': typeof ManualHubRoute
  '/panduan': typeof PanduanRoute
  '/pustaka-regulasi': typeof PustakaRegulasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/insight-hub/$slug': typeof InsightHubSlugRoute
  '/manual-hub/$slug': typeof ManualHubSlugRoute
  '/pustaka-regulasi/$slug': typeof PustakaRegulasiSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/insight-hub': typeof InsightHubRoute
  '/manual-hub': typeof ManualHubRoute
  '/panduan': typeof PanduanRoute
  '/pustaka-regulasi': typeof PustakaRegulasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/insight-hub_/$slug': typeof InsightHubSlugRoute
  '/manual-hub_/$slug': typeof ManualHubSlugRoute
  '/pustaka-regulasi_/$slug': typeof PustakaRegulasiSlugRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/insight-hub'
    | '/manual-hub'
    | '/panduan'
    | '/pustaka-regulasi'
    | '/sitemap.xml'
    | '/tentang'
    | '/insight-hub/$slug'
    | '/manual-hub/$slug'
    | '/pustaka-regulasi/$slug'
    | '/studio/$'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/insight-hub'
    | '/manual-hub'
    | '/panduan'
    | '/pustaka-regulasi'
    | '/sitemap.xml'
    | '/tentang'
    | '/insight-hub/$slug'
    | '/manual-hub/$slug'
    | '/pustaka-regulasi/$slug'
    | '/studio/$'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/insight-hub'
    | '/manual-hub'
    | '/panduan'
    | '/pustaka-regulasi'
    | '/sitemap.xml'
    | '/tentang'
    | '/insight-hub_/$slug'
    | '/manual-hub_/$slug'
    | '/pustaka-regulasi_/$slug'
    | '/studio/$'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  InsightHubRoute: typeof InsightHubRoute
  ManualHubRoute: typeof ManualHubRoute
  PanduanRoute: typeof PanduanRoute
  PustakaRegulasiRoute: typeof PustakaRegulasiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
  InsightHubSlugRoute: typeof InsightHubSlugRoute
  ManualHubSlugRoute: typeof ManualHubSlugRoute
  PustakaRegulasiSlugRoute: typeof PustakaRegulasiSlugRoute
  StudioSplatRoute: typeof StudioSplatRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pustaka-regulasi': {
      id: '/pustaka-regulasi'
      path: '/pustaka-regulasi'
      fullPath: '/pustaka-regulasi'
      preLoaderRoute: typeof PustakaRegulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-hub': {
      id: '/manual-hub'
      path: '/manual-hub'
      fullPath: '/manual-hub'
      preLoaderRoute: typeof ManualHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight-hub': {
      id: '/insight-hub'
      path: '/insight-hub'
      fullPath: '/insight-hub'
      preLoaderRoute: typeof InsightHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/studio/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pustaka-regulasi_/$slug': {
      id: '/pustaka-regulasi_/$slug'
      path: '/pustaka-regulasi/$slug'
      fullPath: '/pustaka-regulasi/$slug'
      preLoaderRoute: typeof PustakaRegulasiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-hub_/$slug': {
      id: '/manual-hub_/$slug'
      path: '/manual-hub/$slug'
      fullPath: '/manual-hub/$slug'
      preLoaderRoute: typeof ManualHubSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight-hub_/$slug': {
      id: '/insight-hub_/$slug'
      path: '/insight-hub/$slug'
      fullPath: '/insight-hub/$slug'
      preLoaderRoute: typeof InsightHubSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  InsightHubRoute: InsightHubRoute,
  ManualHubRoute: ManualHubRoute,
  PanduanRoute: PanduanRoute,
  PustakaRegulasiRoute: PustakaRegulasiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
  InsightHubSlugRoute: InsightHubSlugRoute,
  ManualHubSlugRoute: ManualHubSlugRoute,
  PustakaRegulasiSlugRoute: PustakaRegulasiSlugRoute,
  StudioSplatRoute: StudioSplatRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
