/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PustakaRegulasiRouteImport } from './routes/pustaka-regulasi'
import { Route as ManualHubRouteImport } from './routes/manual-hub'
import { Route as InsightHubRouteImport } from './routes/insight-hub'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightHubSlugRouteImport } from './routes/insight-hub.$slug'

const PustakaRegulasiRoute = PustakaRegulasiRouteImport.update({
  id: '/pustaka-regulasi',
  path: '/pustaka-regulasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualHubRoute = ManualHubRouteImport.update({
  id: '/manual-hub',
  path: '/manual-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightHubRoute = InsightHubRouteImport.update({
  id: '/insight-hub',
  path: '/insight-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightHubSlugRoute = InsightHubSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightHubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/insight-hub': typeof InsightHubRouteWithChildren
  '/manual-hub': typeof ManualHubRoute
  '/pustaka-regulasi': typeof PustakaRegulasiRoute
  '/insight-hub/$slug': typeof InsightHubSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/insight-hub': typeof InsightHubRouteWithChildren
  '/manual-hub': typeof ManualHubRoute
  '/pustaka-regulasi': typeof PustakaRegulasiRoute
  '/insight-hub/$slug': typeof InsightHubSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/insight-hub': typeof InsightHubRouteWithChildren
  '/manual-hub': typeof ManualHubRoute
  '/pustaka-regulasi': typeof PustakaRegulasiRoute
  '/insight-hub/$slug': typeof InsightHubSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/insight-hub'
    | '/manual-hub'
    | '/pustaka-regulasi'
    | '/insight-hub/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/insight-hub'
    | '/manual-hub'
    | '/pustaka-regulasi'
    | '/insight-hub/$slug'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/insight-hub'
    | '/manual-hub'
    | '/pustaka-regulasi'
    | '/insight-hub/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  InsightHubRoute: typeof InsightHubRouteWithChildren
  ManualHubRoute: typeof ManualHubRoute
  PustakaRegulasiRoute: typeof PustakaRegulasiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pustaka-regulasi': {
      id: '/pustaka-regulasi'
      path: '/pustaka-regulasi'
      fullPath: '/pustaka-regulasi'
      preLoaderRoute: typeof PustakaRegulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-hub': {
      id: '/manual-hub'
      path: '/manual-hub'
      fullPath: '/manual-hub'
      preLoaderRoute: typeof ManualHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight-hub': {
      id: '/insight-hub'
      path: '/insight-hub'
      fullPath: '/insight-hub'
      preLoaderRoute: typeof InsightHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight-hub/$slug': {
      id: '/insight-hub/$slug'
      path: '/$slug'
      fullPath: '/insight-hub/$slug'
      preLoaderRoute: typeof InsightHubSlugRouteImport
      parentRoute: typeof InsightHubRoute
    }
  }
}

interface InsightHubRouteChildren {
  InsightHubSlugRoute: typeof InsightHubSlugRoute
}

const InsightHubRouteChildren: InsightHubRouteChildren = {
  InsightHubSlugRoute: InsightHubSlugRoute,
}

const InsightHubRouteWithChildren = InsightHubRoute._addFileChildren(
  InsightHubRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  InsightHubRoute: InsightHubRouteWithChildren,
  ManualHubRoute: ManualHubRoute,
  PustakaRegulasiRoute: PustakaRegulasiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
